# Generated by Django 2.2.7 on 2021-11-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('0', 'boss'), ('1', 'artist'), ('2', 'normal')], default='2', max_length=10),
        ),
    ]
