# Generated by Django 2.2.7 on 2021-12-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20211202_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
